# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import pymysql
import sys, os
import ctypes
import easygui as e
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

os.environ["CUDA_VISIBLE_DEVICES"] = "-1"


class Ui_MainWindow(object):
    def __init__(self):
        self.login_state = False

    def under_construction(self):
        QMessageBox.information(MainWindow, "HOPE CHAT", "此功能出现了问题！如要注册账号\n请邮箱\ngxbf1130wsr@outlook.com！",
                                QMessageBox.Ok)

    def chat(self):
        if self.login_state == True:
            QMessageBox.information(MainWindow, "HOPE CHAT", "关闭此窗口以使用HOPE CHAT",
                                    QMessageBox.Ok)
            MainWindow.close()
            os.system(f"client.exe {self.name}")
            sys.exit()
        else:
            QMessageBox.warning(MainWindow, "HOPE CHAT", "无效的会话id\n请尝试重新登陆HOPE CHAT账号或重启HOPE CHAT",
                                QMessageBox.Ok)

    def login(self):
        # get data
        self.db = pymysql.connect(host="frp-box.top", port=27425, user="root", password="code0808", database="staff")
        self.cursor = self.db.cursor()
        self.sql = "select * from tb"
        self.cursor.execute(self.sql)
        log = self.cursor.fetchall()

        # login
        self.name = self.lineEdit.text()
        self.psw = self.lineEdit_2.text()
        for i in log:
            if i[0] == self.name and i[1] == self.psw:
                self.login_state = True
                self.label_4.setText("用户名称："+i[0])
                self.label_2.setVisible(False)
                self.label_3.setVisible(False)
                self.lineEdit.setVisible(False)
                self.lineEdit_2.setVisible(False)
                self.pushButton.setVisible(False)
                self.reg.setVisible(False)
                self.reg_text.setText(self.name + "，你今天看起来很聪明！")
                self.reg_text.setGeometry(QtCore.QRect(30, 200, 350, 27))
                QMessageBox.information(MainWindow, "HOPE CHAT", "欢迎，"+i[0],
                                        QMessageBox.Ok)

        if self.login_state is False:
            QMessageBox.information(MainWindow, "HOPE CHAT", "账户或密码错误！",
                                    QMessageBox.Ok)
        self.cursor.close()
        self.db.close()

    def register(self):
        db = pymysql.connect(host="frp-box.top", port=27425, user="root", password="code0808", database="staff")
        cursor = db.cursor()
        reg_name = e.enterbox("请输入名称：")
        reg_psw = e.enterbox("请输入密码：")
        reg_psw2 = e.enterbox("请确认密码：")
        if reg_name and reg_psw and reg_psw2:
            if reg_psw == reg_psw2:
                query = 'INSERT INTO tb (`name`, `psw`) VALUES (%s, %s)'
                cursor.execute(query, (reg_name, reg_psw))
                db.commit()
                QMessageBox.information(MainWindow, "HOPE CHAT", "注册成功！您现在可以使用HOPE-CHAT-ALPHA了！",
                                        QMessageBox.Ok)
            else:
                QMessageBox.information(MainWindow, "HOPE CHAT", "两次密码输入不一致！",
                                        QMessageBox.Ok)
        else:
            QMessageBox.information(MainWindow, "HOPE CHAT", "输入内容不能为空，搁这卡Bug呢~",
                                    QMessageBox.Ok)
        cursor.close()
        db.close()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(int(1920/2), int(1080/2))
        MainWindow.setWindowIcon(QtGui.QIcon("hope-chat.ico"))
        ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID("myappid")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 10, 700, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.web = QtWidgets.QLabel(self.centralwidget)
        self.web.setGeometry(QtCore.QRect(500, 200, 357, 120))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.web.setFont(font)
        self.web.setObjectName("web")
        self.web.setStyleSheet("color:#ff1030")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(270, 180, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.login)
        self.reg = QtWidgets.QPushButton(self.centralwidget)
        self.reg.setGeometry(QtCore.QRect(270, 250, 130, 30))
        self.reg.setObjectName("reg")
        self.reg.clicked.connect(self.register)
        self.reg_text = QtWidgets.QLabel(self.centralwidget)
        self.reg_text.setGeometry(QtCore.QRect(30, 250, 232, 27))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.reg_text.setFont(font)
        self.reg_text.setObjectName("reg_text")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(250, 90, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(250, 140, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 90, 81, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 140, 81, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(480, 100, 400, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 330, 111, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.chat)
        self.copr = QtWidgets.QLabel(self.centralwidget)
        self.copr.setGeometry(QtCore.QRect(30, 450, 700, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 624, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HOPE-CHAT-ALPHA-1.6.0"))
        self.label.setText(_translate("MainWindow", "HOPE-CHAT-ALPHA-1.6.0"))
        self.pushButton.setText(_translate("MainWindow", "登录"))
        self.label_2.setText(_translate("MainWindow", "账号："))
        self.web.setText(_translate("MainWindow", "注册功能已经开发完毕！\n不再卡退！"))
        self.label_3.setText(_translate("MainWindow", "密码："))
        self.label_4.setText(_translate("MainWindow", "HOPE CHAT:未登录"))
        self.pushButton_2.setText(_translate("MainWindow", "开始聊天！"))
        self.reg.setText(_translate("MainWindow", "注册一个！"))
        self.reg_text.setText(_translate("MainWindow", "还没有HOPE CHAT账号？"))
        # self.copr.setText(_translate("MainWindow", "Copyright ©2023-2023 HopeStudio, All Rights Reserved.严惩盗版用户！"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
